// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRBO4p_LIrGv4ePaMpM92T_E3smpOibw',
    appId: '1:764805872612:web:6a4e09da407cc3db6b25f1',
    messagingSenderId: '764805872612',
    projectId: 'digibinn-20537',
    authDomain: 'digibinn-20537.firebaseapp.com',
    databaseURL: 'https://digibinn-20537-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digibinn-20537.appspot.com',
    measurementId: 'G-EHNBQ4KS9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAh2eiwG-dH-ln4uYC5GhUJFo0zQp3CWc',
    appId: '1:764805872612:android:1fb0d8fbb00f9dd46b25f1',
    messagingSenderId: '764805872612',
    projectId: 'digibinn-20537',
    databaseURL: 'https://digibinn-20537-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digibinn-20537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9JsHjkcJ85m_YRNvF2WWzlno8lte_WSg',
    appId: '1:764805872612:ios:f9a7d41cc65e0abd6b25f1',
    messagingSenderId: '764805872612',
    projectId: 'digibinn-20537',
    databaseURL: 'https://digibinn-20537-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digibinn-20537.appspot.com',
    iosClientId: '764805872612-evu9curpubra160jfn51fkii407frnab.apps.googleusercontent.com',
    iosBundleId: 'com.example.digibinnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9JsHjkcJ85m_YRNvF2WWzlno8lte_WSg',
    appId: '1:764805872612:ios:f9a7d41cc65e0abd6b25f1',
    messagingSenderId: '764805872612',
    projectId: 'digibinn-20537',
    databaseURL: 'https://digibinn-20537-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digibinn-20537.appspot.com',
    iosClientId: '764805872612-evu9curpubra160jfn51fkii407frnab.apps.googleusercontent.com',
    iosBundleId: 'com.example.digibinnApp',
  );
}
